---
language: node_js
node_js:
  - "6"

dist: xenial

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.yarn

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - yarn test
